# Generated by Django 3.2.6 on 2022-08-05 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_like_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pop',
            name='date_added',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cloths', 'cloths'), ('shoes', 'shoes'), ('fairly used laptops', 'fairly used laptops')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], default='like', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
