# Generated by Django 3.2.6 on 2022-08-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220805_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], default='like', max_length=10),
        ),
    ]
